name:                haskell-arduino-p05-mood-cue
version:             0.1.0.0
github:              "githubuser/haskell-arduino-p05-mood-cue"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-arduino-p05-mood-cue#readme>

dependencies:
- base >= 4.7 && < 5
- arduino-copilot

library:
  source-dirs: src
  default-extensions:
  - RebindableSyntax

executables:
  haskell-arduino-p05-mood-cue-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-arduino-p05-mood-cue

tests:
  haskell-arduino-p05-mood-cue-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-arduino-p05-mood-cue
